@startuml
start
:Вікно авторизації;
:Введення логіну<
:Введення паролю<
:Підтвердження введених даних<
:Надсилання запиту на сервер;
:Обробка запиту;
if (Чи існує такий користувач?) then (Так)
    :Відображення особистого кабінету>
else(Ні)
    :Вивід повідомлення про збій>
endif
stop
@enduml