@startuml
start
if (Чи запланував користувач хоча б 1 консультацію?) then (Так)
    :Відображення списку запланованих користувачем консультацій;
    :Вибір тих консультацій, які необхідно скасувати<
    :Підтвердження скасування> 
    :Надсилання запиту на сервер;
    :Обробка запиту;
    :Видалення запису про консультацію з відповідного поля таблиці Visits>
else (Ні)
    :Вивід повідомлення про відсутність запланованих консультацій>  
endif
stop
@enduml