@startuml
left to right direction
Користувач --> (Реєстрація)
Користувач --> (Авторизація)
(Авторизація) --> Авторизований_користувач
Авторизований_користувач -[#Blue]-> Сервер
Авторизований_користувач --> (Вихід)
Сервер -[#Blue]-> (Перегляд особистої мед-карти)
Сервер -[#Blue]-> (Перегляд годин, коли лікар зайнятий)
Авторизований_користувач --> (Реєстрація на прийом)
Авторизований_користувач --> (Відміна реєстрації на прийом)
(Реєстрація на прийом) --> Сервер
(Відміна реєстрації на прийом) --> Сервер
@enduml
