@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <u>x</u>
hide methods
hide stereotypes

table(Accounts) {
  primary_key(Login)
  Password
}

table(Doctors) {
  Name
  primary_key(Surname)
  Cabinet
}

table(MedicalHistory) {
  Login
  Name
  Surname
  Date
  Diagnosis
  primary_key(DoctorsReccomendation)
}

table(Visits) {
  primary_key(ID)
  Name
  Surname
  Cabinet
  DateTime
  Login
}
@enduml
