@startuml
start
:Надсилання запиту на сервер;
:Обробка запиту;
if (Чи існує такий лікар?) then (Так)
    if (Чи заплановані у лікаря консультації?) then (Так)
        :Відображення інформації про заплановані консультації>
    else(Ні)
        :Повідомити про те, що лікар вільний у будь який час>
    endif
else(Ні)
    :Повідомити про те що такого лікаря не існує>
endif
stop
@enduml