@startuml
start
:Вікно реєстрації на консультацію;
:Введення прізвища лікаря<
:Вибір дати прийому<
:Вибір часу прийому<
:Надсилання запиту на сервер;
:Обробка запиту;
if (Прізвиче лікаря введено корректно?) then (Так)
    if (Чи вільний лікар вказаного дня у вказаний час?) then (Так)
        :Занести дані про консультацію у відповідні поля таблиці Visits>
    else(Ні)
        :Повідомити про збій>
    endif
else(Ні)
    :Повідомити про збій>
endif
stop
@enduml