@startuml
start
:Вікно реєстрації;
:Введення логіну<
:Введення паролю<
if (Чи існує такий користувач?) then (Так)
    :Вивід повідомлення про збій>
else (Ні)
    :Внесення особистих даних нового користувача у відповідні поля таблиці Accounts>
endif
stop
@enduml