@startuml
start
:Надсилання запиту на сервер;
:Обробка запиту;
if (Дані про користувача є у таблиці MedHistory?) then (Так)
    :Відображення мед-карти>
else(Ні)
    :Повідомити про відсутність записів>
endif
stop
@enduml